// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PT.Data.Contexts;

#nullable disable

namespace PT.Data.Migrations
{
    [DbContext(typeof(PortfolioTrackerDbContext))]
    partial class PortfolioTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PT.Data.Entities.Investment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PricePerUnit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Investments");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            ActionType = "Buy",
                            Amount = 2,
                            AssetType = "Crypto",
                            Date = new DateOnly(2025, 8, 24),
                            Name = "Bitcoin",
                            PricePerUnit = 323232
                        },
                        new
                        {
                            Id = -2,
                            ActionType = "Buy",
                            Amount = 4,
                            AssetType = "Crypto",
                            Date = new DateOnly(2025, 8, 24),
                            Name = "Ethereum",
                            PricePerUnit = 4231
                        },
                        new
                        {
                            Id = -3,
                            ActionType = "Buy",
                            Amount = 2,
                            AssetType = "Stock",
                            Date = new DateOnly(2025, 8, 24),
                            Name = "Tesla Inc.",
                            PricePerUnit = 340
                        },
                        new
                        {
                            Id = -4,
                            ActionType = "Buy",
                            Amount = 10,
                            AssetType = "Metal",
                            Date = new DateOnly(2025, 8, 24),
                            Name = "Gold",
                            PricePerUnit = 3372
                        },
                        new
                        {
                            Id = -5,
                            ActionType = "Buy",
                            Amount = 1,
                            AssetType = "Metal",
                            Date = new DateOnly(2025, 8, 24),
                            Name = "Silver",
                            PricePerUnit = 150
                        },
                        new
                        {
                            Id = -6,
                            ActionType = "Buy",
                            Amount = 5,
                            AssetType = "Stock",
                            Date = new DateOnly(2025, 8, 24),
                            Name = "Microsoft",
                            PricePerUnit = 500
                        },
                        new
                        {
                            Id = -7,
                            ActionType = "Buy",
                            Amount = 6,
                            AssetType = "Stock",
                            Date = new DateOnly(2025, 8, 24),
                            Name = "IBM",
                            PricePerUnit = 240
                        },
                        new
                        {
                            Id = -8,
                            ActionType = "Buy",
                            Amount = 10,
                            AssetType = "Stock",
                            Date = new DateOnly(2025, 8, 24),
                            Name = "NVDA",
                            PricePerUnit = 3450
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
